# ===================================================================
# Spring Boot configuration for the "dev" profile.
# This configuration overrides the application.yml file.
# ===================================================================

spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  main:
    banner-mode: on      
  cache:
    jcache:
      config: ehcache.xml

endpoints:
  cors:
    allowed-origins: 
    allow-credentials: true

      
server:
    contextPath: /
    
security:
  basic:
    enable: false
       
management:
  security:
    enabled: false

