# ===================================================================
# Spring Boot configuration for the "dev" profile.
# This configuration overrides the application.yml file.
# ===================================================================

spring:
  profiles:
    active: dev
  jackson:
    serialization:
      INDENT_OUTPUT: true
  main:
    banner-mode: on      
  cache:
    jcache:
      config: ehcache.xml
  datasource:
    hikari:
      pool-name: EliteHikariCP
      maximum-pool-size: 5
      driver-class-name: oracle.jdbc.OracleDriver
      connection-init-sql: SELECT 1 FROM DUAL
      connection-test-query: SELECT 1 FROM DUAL
      #jdbc-url: jdbc:oracle:thin:@db-rh-s5.syscon.ca:1521:ndd11dv1
      #jdbc-url: jdbc:oracle:thin:@wndbsvsdaqas01.syscon.ca:1521:sdprobi1
      jdbc-url: jdbc:oracle:thin:@prod-12c-dev.syscon.ca:1521:pb12cdv1
      username: oms_owner
      password: oms_owner
      idle-timeout: 10000
      oracle-proxy: true
logging:
  level:
    org.springframework.security: INFO
jwt:
  header: Authorization
  secret: my-very-secret-key

endpoints:
  cors:
    allowed-origins: 
    allow-credentials: true

server:
    port: 7080
    contextPath: /
    
security:
  basic:
    enable: false
       
management:
  security:
    enabled: false

