---
exclude_paths:
  - 'elite2-api/src/main/configs/**'
  - '**.sql'
  - '/elite2-api/src/main/java/net/syscon/elite/api/resource/impl/PrisonerResourceImpl.java'
  
  # see https://support.codacy.com/hc/en-us/articles/115002130625-Codacy-Configuration-File