version: '3.1'
services:
  elite2-web:
    image: sysconjusticesystems/elite2-web:demo-latest
    networks:
      - azure
    depends_on:
      - elite2-api
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
    deploy:
        replicas: 1
        update_config:
          parallelism: 1
          delay: 10s
        restart_policy:
          condition: on-failure
        placement:
          constraints: [node.role == worker]
    environment:
      - PORT=3000
      - API_ENDPOINT_URL=http://elite2-api:8080/api/
      - USE_API_GATEWAY_AUTH=no
      - GOOGLE_ANALYTICS_ID=UA-106741063-3
      - WEB_SESSION_TIMEOUT_IN_MINUTES=120
      - NOMS_TOKEN=secret_token

  elite2-api:
    image: sysconjusticesystems/elite2-api:latest
    networks:
      - azure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/info/health"]
    deploy:
        replicas: 1
        update_config:
          parallelism: 1
          delay: 10s
        restart_policy:
          condition: on-failure
        placement:
          constraints: [node.role == worker]
    environment:
      - JAVA_OPTS=-Xmx1024m
      - SPRING_PROFILES_ACTIVE=nomis-oracle
      - JWT_SIGNING_KEY=demosecretkey
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@terraform-20171216091202578200000001.cuo8tj8nysnb.eu-west-2.rds.amazonaws.com:1521:TESTDB
      - ORACLE_DEFAULT_SCHEMA=DEMO_NOMIS_OWNER
      - SPRING_DATASOURCE_username=api_proxy_user
      - SPRING_DATASOURCE_password=api_proxy_user

networks:
  azure:
