server:
  servlet:
    context-path: /elite2api
  use-forward-headers: true
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol_header: x-forwarded-proto

# ===================================================================
# Standard Spring Boot configuration
# ===================================================================

spring:

  datasource:
    continueOnError: true

    hikari:
      pool-name: Elite2-CP
      connectionTimeout: 1000
      validationTimeout:  500

  jersey:
    type: servlet
    application-path: /api


logging:
  level:
    org.springframework.security: INFO
