server:
  port: 8080

spring:
  application:
    name: elite2-api

  jersey:
    type: servlet
    application-path: /api

logging:
  level:
    org.springframework.security: INFO

management:
  endpoints:
    web:
      base-path: /
