server:
  port: 8080

spring:
  datasource:
    continueOnError: true

    hikari:
      pool-name: Elite2-CP
      connectionTimeout: 1000
      validationTimeout:  500

  jersey:
    type: servlet
    application-path: /api

logging:
  level:
    org.springframework.security: INFO

management:
  endpoints:
    web:
      base-path: /
