server:
  port: 8080

spring:
  datasource:
    continueOnError: true

    hikari:
      maximum-pool-size: 10
      connectionTimeout: 1000
      validationTimeout:  500

  replica:
    datasource:
      hikari:
        maximum-pool-size: 10
        connectionTimeout: 1000
        validationTimeout:  500

  jersey:
    type: servlet
    application-path: /api

logging:
  level:
    org.springframework.security: INFO

management:
  endpoints:
    web:
      base-path: /
