# ===================================================================
# Standard Spring Boot configuration
# ===================================================================

spring:

  profiles:
    active: dev
    
  jackson:
    serialization:
      INDENT_OUTPUT: false

  datasource:
    hikari:
      pool-name: EliteCP
      maximum-pool-size: 5
      driver-class-name: oracle.jdbc.OracleDriver
      connection-init-sql: SELECT 1 FROM DUAL
      connection-test-query: SELECT 1 FROM DUAL
      #jdbc-url: jdbc:oracle:thin:@db-rh-s5.syscon.ca:1521:ndd11dv1
      jdbc-url: jdbc:oracle:thin:@prod-12c-dev.syscon.ca:1521:pb12cdv1
      username: oms_owner
      password: oms_owner
      idle-timeout: 10000
      oracle-proxy: true

jwt:
  header: Authorization
  secret: s3cre3tK3y
  expiration: 1000

logging:
  level:
    org.springframework.security: INFO
  cache:
    jcache:
      config: ehcache.xml
      
  mail:
    host: localhost
    port: 25
    username:
    password:
    
  messages:
    cache-seconds: 1

    
liquibase:
    contexts: dev

server:
    port: 8080
    contextPath: /elite2

endpoints:
  cors:
    allowed-origins: http://localhost:7080
    allow-credentials: true
    allow-headers: Origin, X-Requested-With, Content-Type, Accept, X-Auth-Token
