# ===================================================================
# Standard Spring Boot configuration
# ===================================================================

spring:

  datasource:
    continueOnError: true
    initialize: false
    initialSize: 0
    timeBetweenEvictionRunsMillis: ${conn.pool.idle.timeout}
    minEvictableIdleTimeMillis: ${conn.pool.idle.timeout}
    minIdle: 0
    maxActive: ${conn.pool.max.size}
    validationQuery: SELECT 1 FROM DUAL
    maxWait: 10000

  application:
    index: api.html

security:
  basic:
    enable: false
  jwt:
    header: Authorization
    signingKey: ${jwt.signing.key}
    schema: Bearer
    expiration: ${jwt.expiration.seconds} # Number of seconds
    refreshExpiration: ${jwt.refresh.expiration.seconds} # Number of seconds
    issuer: http://www.syscon.net


logging:
  level:
    org.springframework.security: INFO
      
  mail:
    host: localhost
    port: 25
    username:
    password:
    
  messages:
    cache-seconds: 1

server:
    contextPath: /api

endpoints:
  cors:
    allowed-origins: ${cors.allowed-origins}
    allow-credentials: true
    allow-headers: Origin,X-Requested-With,Content-Type,Accept,Authorization
    allow-methods: GET,PUT,POST,DELETE