# ===================================================================
# Standard Spring Boot configuration
# ===================================================================

spring:

  datasource:
    continueOnError: true
    initialize: false
    initialSize: 0
    timeBetweenEvictionRunsMillis: ${conn.pool.idle.timeout}
    minEvictableIdleTimeMillis: ${conn.pool.idle.timeout}
    minIdle: 0
    maxActive: ${conn.pool.max.size}
    validationQuery: SELECT 1 FROM DUAL
    maxWait: 10000

  application:
    index: api.html

  jersey:
    type: filter


logging:
  level:
    org.springframework.security: INFO

    
  messages:
    cache-seconds: 1

server:
    contextPath: /