# ===================================================================
# Standard Spring Boot configuration
# ===================================================================

spring:

  jackson:
    serialization:
      INDENT_OUTPUT: false

  datasource:
      hikari:
        pool-name: EliteCP
        maximum-pool-size: ${conn.pool.max.size}
        driver-class-name: ${spring.datasource.driver-class-name}
        connection-init-sql: SELECT 1 FROM DUAL
        jdbc-url: ${spring.datasource.url}
        username: ${spring.datasource.username}
        password: ${spring.datasource.password}
        idle-timeout: ${conn.pool.idle.timeout}
        oracle-proxy.enabled: true

  application:
    index: api.html

security:
  basic:
    enable: false
  jwt:
    header: Authorization
    signingKey: s3cre3tK3y
    schema: Bearer
    expiration: 10 # Number of minutes
    refreshExpiration: 60 # Number of minutes
    issuer: http://www.syscon.net


logging:
  level:
    org.springframework.security: INFO
  cache:
    jcache:
      config: ehcache.xml
      
  mail:
    host: localhost
    port: 25
    username:
    password:
    
  messages:
    cache-seconds: 1

server:
    contextPath: /

endpoints:
  cors:
    allowed-origins: http://localhost:${server.port}
    allow-credentials: true
    allow-headers: Origin, X-Requested-With, Content-Type, Accept, Authorization
