version: 2
jobs:
  build:
    working_directory: ~/circleci-elite2-api
    docker:
      - image: circleci/openjdk:8-jdk-browsers
      - image: docker:1.13.1-git
    steps:
      - checkout
      - run: ./gradlew -Poracle11 build -x integTest
      - store_test_results:
          path: mobile-web/build/test-results
      - store_artifacts:
          path: mobile-web/build/libs/mobile-web-1.0-SNAPSHOT.jar
      - setup_remote_docker
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t sysconjusticesystems/elite2-api:$TAG .
          docker tag sysconjusticesystems/elite2-api:$TAG sysconjusticesystems/elite2-api:latest
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push sysconjusticesystems/elite2-api:$TAG
          docker push sysconjusticesystems/elite2-api:latest
